module.exports = {
  CarListing: require('./CarListing'),
  Tyres: require('./Tyres'),
  Media: require('./Media'),
  DimensionsCapacity: require('./DimensionsCapacity'),
  EngineTransmission: require('./EngineTransmission'),
  FuelPerformance: require('./FuelPerformance'),
  SuspensionSteeringBrakes: require('./SuspensionSteeringBrakes'),
  BookingPolicy: require('./BookingPolicy'),
  CarFeatures: require('./CarFeatures'),
  Review: require('./Review'),
  LoveStory: require('./LoveStory'),
  Faq: require('./Faq'),
  SellCar: require('./SellCar'),
  TestDriveBooking: require('./TestDriveBooking'),
  CallbackRequest: require('./CallbackRequest'),
  User: require('./User'),
  Otp: require('./Otp'),
  RecentCarView: require('./RecentCarView'),
};
